homeassistant_latitude: 000.0000000
homeassistant_longitude: 000.0000000
homeassistant_elevation: 00
forecast_key: ForcastKeyphrase
MQTT_server: someserverthisis.com
MQTT_username: MQTT_username
MQTT_password: password
configurator_server: thatSuperServer
ssh_server: thatEvenMoreSuperServer
